# Generated by Django 4.0.5 on 2022-07-04 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessApp', '0002_alter_brands_name_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_released', models.DateField()),
                ('post', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tax_code', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
                ('contact', models.EmailField(max_length=254)),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('sinopsis', models.CharField(max_length=50)),
                ('mark', models.IntegerField()),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('genre_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusinessApp.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('delivery_address', models.CharField(max_length=20)),
                ('delivery_date', models.DateField()),
                ('active', models.BooleanField()),
                ('movie_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_title', to='BusinessApp.movie')),
                ('price_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusinessApp.movie')),
            ],
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Purchase_order',
        ),
        migrations.DeleteModel(
            name='Suppliers',
        ),
    ]
