# Generated by Django 4.0.5 on 2022-07-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessApp', '0003_blog_client_genre_movie_ticket_delete_brands_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
