# Generated by Django 4.0.5 on 2022-07-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessApp', '0004_alter_movie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
