# Generated by Django 4.0.5 on 2022-07-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessApp', '0006_alter_blog_created_at_alter_blog_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
